import type { Role, SignalementStatus, SignalementCategory, ProjectStatus } from "@/generated/prisma";

export const SIGNALEMENT_CATEGORIES: Record<SignalementCategory, string> = {
  URBANISME: "Urbanisme",
  TRANSPORT: "Transport",
  ENVIRONNEMENT: "Environnement",
  VOIRIE: "Voirie",
  EAU: "Eau",
  DECHETS: "Déchets",
  EQUIPEMENTS_PUBLICS: "Équipements publics",
  SANTE: "Santé",
  EDUCATION: "Éducation",
};

export const SIGNALEMENT_STATUSES: Record<SignalementStatus, string> = {
  RECU: "Reçu",
  EN_COURS: "En cours de traitement",
  PRIS_EN_CHARGE: "Pris en charge",
  RESOLU: "Résolu",
  REJETE: "Rejeté",
};

export const PROJECT_STATUSES: Record<ProjectStatus, string> = {
  EN_ATTENTE: "En attente",
  EN_COURS: "En cours",
  SUSPENDU: "Suspendu",
  TERMINE: "Terminé",
  ANNULE: "Annulé",
};

export const ROLE_LABELS: Record<Role, string> = {
  SUPER_ADMIN: "Super Administrateur",
  ADMIN_MINISTERE: "Administrateur Ministère",
  ADMIN_WILAYA: "Administrateur Wilaya",
  GESTIONNAIRE_TERRITORIAL: "Gestionnaire Territorial",
  AGENT_TECHNIQUE: "Agent Technique",
  CITOYEN: "Citoyen",
};

export const ADMIN_ROLES: Role[] = [
  "SUPER_ADMIN",
  "ADMIN_MINISTERE",
  "ADMIN_WILAYA",
  "GESTIONNAIRE_TERRITORIAL",
  "AGENT_TECHNIQUE",
];

export const WILAYA_CENTERS: Record<string, { lat: number; lng: number; zoom: number }> = {
  "Adrar":               { lat: 27.87,  lng: -0.29,  zoom: 8 },
  "Chlef":               { lat: 36.17,  lng:  1.33,  zoom: 10 },
  "Laghouat":            { lat: 33.80,  lng:  2.87,  zoom: 9 },
  "Oum El Bouaghi":      { lat: 35.88,  lng:  7.11,  zoom: 10 },
  "Batna":               { lat: 35.55,  lng:  6.17,  zoom: 10 },
  "Béjaïa":              { lat: 36.75,  lng:  5.08,  zoom: 10 },
  "Biskra":              { lat: 34.85,  lng:  5.73,  zoom: 9 },
  "Béchar":              { lat: 31.62,  lng: -2.22,  zoom: 8 },
  "Blida":               { lat: 36.47,  lng:  2.83,  zoom: 11 },
  "Bouira":              { lat: 36.37,  lng:  3.90,  zoom: 10 },
  "Tamanrasset":         { lat: 22.79,  lng:  5.52,  zoom: 7 },
  "Tébessa":             { lat: 35.40,  lng:  8.12,  zoom: 10 },
  "Tlemcen":             { lat: 34.88,  lng: -1.32,  zoom: 10 },
  "Tiaret":              { lat: 35.37,  lng:  1.32,  zoom: 10 },
  "Tizi Ouzou":          { lat: 36.71,  lng:  4.05,  zoom: 10 },
  "Alger":               { lat: 36.74,  lng:  3.06,  zoom: 12 },
  "Djelfa":              { lat: 34.67,  lng:  3.26,  zoom: 9 },
  "Jijel":               { lat: 36.82,  lng:  5.77,  zoom: 10 },
  "Sétif":               { lat: 36.19,  lng:  5.41,  zoom: 10 },
  "Saïda":               { lat: 34.83,  lng:  0.15,  zoom: 10 },
  "Skikda":              { lat: 36.87,  lng:  6.90,  zoom: 10 },
  "Sidi Bel Abbès":      { lat: 35.19,  lng: -0.63,  zoom: 10 },
  "Annaba":              { lat: 36.90,  lng:  7.75,  zoom: 11 },
  "Guelma":              { lat: 36.46,  lng:  7.43,  zoom: 10 },
  "Constantine":         { lat: 36.37,  lng:  6.62,  zoom: 11 },
  "Médéa":               { lat: 36.26,  lng:  2.76,  zoom: 10 },
  "Mostaganem":          { lat: 35.93,  lng:  0.09,  zoom: 11 },
  "M'Sila":              { lat: 35.70,  lng:  4.55,  zoom: 9 },
  "Mascara":             { lat: 35.39,  lng:  0.14,  zoom: 10 },
  "Ouargla":             { lat: 31.95,  lng:  5.32,  zoom: 8 },
  "Oran":                { lat: 35.69,  lng: -0.64,  zoom: 11 },
  "El Bayadh":           { lat: 33.68,  lng:  1.01,  zoom: 9 },
  "Illizi":              { lat: 26.50,  lng:  8.48,  zoom: 7 },
  "Bordj Bou Arréridj":  { lat: 36.07,  lng:  4.76,  zoom: 10 },
  "Boumerdès":           { lat: 36.76,  lng:  3.48,  zoom: 11 },
  "El Tarf":             { lat: 36.77,  lng:  8.31,  zoom: 10 },
  "Tindouf":             { lat: 27.67,  lng: -8.15,  zoom: 8 },
  "Tissemsilt":          { lat: 35.60,  lng:  1.81,  zoom: 10 },
  "El Oued":             { lat: 33.37,  lng:  6.86,  zoom: 9 },
  "Khenchela":           { lat: 35.43,  lng:  7.14,  zoom: 10 },
  "Souk Ahras":          { lat: 36.29,  lng:  7.94,  zoom: 10 },
  "Tipaza":              { lat: 36.59,  lng:  2.45,  zoom: 11 },
  "Mila":                { lat: 36.45,  lng:  6.27,  zoom: 10 },
  "Aïn Defla":           { lat: 36.27,  lng:  1.97,  zoom: 10 },
  "Naâma":               { lat: 33.27,  lng: -0.31,  zoom: 9 },
  "Aïn Témouchent":      { lat: 35.30,  lng: -1.14,  zoom: 10 },
  "Ghardaïa":            { lat: 32.49,  lng:  3.67,  zoom: 9 },
  "Relizane":            { lat: 35.74,  lng:  0.56,  zoom: 10 },
  "Timimoun":            { lat: 29.26,  lng:  0.23,  zoom: 8 },
  "Bordj Badji Mokhtar": { lat: 21.33,  lng:  0.95,  zoom: 8 },
  "Ouled Djellal":       { lat: 34.42,  lng:  5.07,  zoom: 10 },
  "Béni Abbès":          { lat: 30.08,  lng: -2.17,  zoom: 8 },
  "In Salah":            { lat: 27.20,  lng:  2.47,  zoom: 8 },
  "In Guezzam":          { lat: 19.57,  lng:  5.77,  zoom: 8 },
  "Touggourt":           { lat: 33.10,  lng:  6.07,  zoom: 9 },
  "Djanet":              { lat: 24.55,  lng:  9.48,  zoom: 8 },
  "El M'Ghair":          { lat: 33.95,  lng:  5.92,  zoom: 9 },
  "El Meniaa":           { lat: 30.59,  lng:  2.88,  zoom: 9 },
}

export const ALGERIAN_WILAYAS = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra",
  "Béchar", "Blida", "Bouira", "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret",
  "Tizi Ouzou", "Alger", "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda",
  "Sidi Bel Abbès", "Annaba", "Guelma", "Constantine", "Médéa", "Mostaganem",
  "M'Sila", "Mascara", "Ouargla", "Oran", "El Bayadh", "Illizi", "Bordj Bou Arréridj",
  "Boumerdès", "El Tarf", "Tindouf", "Tissemsilt", "El Oued", "Khenchela",
  "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent",
  "Ghardaïa", "Relizane", "Timimoun", "Bordj Badji Mokhtar", "Ouled Djellal",
  "Béni Abbès", "In Salah", "In Guezzam", "Touggourt", "Djanet", "El M'Ghair",
  "El Meniaa",
];
